### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Upstander1234** [Senither/hypixel-discord-chat-bridge#26]
![image](https://user-images.githubusercontent.com/86688002/124330276-e66a1080-db41-11eb-9662-50fc921f9625.png)
I get this message when I try to run node index.js in cmd prompt. Can you please help?

**Comment by Senither** [comment]
You need to install the dependencies using Yarn, the guide in the readme specifies that you should run the `yarn` command to install all the packages the project requires, if you don't have Yarn installed you can install it using `npm install -g yarn`.

**Comment by Upstander1234** [comment]
![image](https://user-images.githubusercontent.com/86688002/124331557-482b7a00-db44-11eb-9f98-10687858e996.png)
I already have yarn installed.

**Comment by Senither** [comment]
That's great, you still haven't installed the packages tho, please read the setup instructions on the readme that actually tells you what to do step by step, or just check my last message that also tells you what to run to install the packages.

**Comment by Senither** [comment]
Here is an example of what you actually need to do.

https://user-images.githubusercontent.com/8415349/124333041-6b314a80-db93-11eb-8f76-c58463dd61d5.mp4

You need to set up the `config.json` file with your account information before the bot will actually work too, I've already done that in the video example above.

**Comment by Upstander1234** [comment]
ah ok ty!
