### ISSUE TITLE
Ingame commands

### ISSUE THREAD

**Issue by Upstander1234** [Senither/hypixel-discord-chat-bridge#29]
I can't seem to find a way to get them to function. Are they released yet?

**Comment by itsneyoa** [comment]
At the moment there's just `!ping` and `!guildlobby`, I've done a bit of testing with commands like `!weight` [here](https://github.com/itsneyoa/hypixel-discord-chat-bridge/blob/commands-testing/src/minecraft/commands/WeightCommand.js) but in my experience it just flooded guild chat and irritated other guild members.

**Comment by itsneyoa** [comment]
I think it would work make commands work in guild and officer chats as well as DMs and build a system to route the replies to the right place. This would also commands in the individual chats to be disabled or enabled in the config (eg [Guild: off, Officer: on, DMs: on] to ensure guild chat isn't cluttered or [Guild: off, Officer: off, DMs: off] to completely disable them). A system like that mixed with something that can extract the api key from the `/api new` message would make adding commands in the future easy and powerful.

**Comment by Upstander1234** [comment]
Ah ok ty!
