### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Ozymandog** [Senither/hypixel-discord-chat-bridge#41]
Haha hey again. This error shows up when I try to run the bot. It's on my old pc that used to have it but I deleted it and now I'm reinstalling it
![Screenshot 2021-10-05 231721](https://user-images.githubusercontent.com/88224228/136150512-a254e535-043f-4b03-9e73-a037f22303d7.png)

aa is just what I renamed hypixel-discord-chat-bridge-master

**Comment by itsneyoa** [comment]
By reinstalling you've updated to the latest version - make sure your `config.json` is up to date with `config.example.json`, it looks like you're missing this block: 
```json
"express": {
  "enabled": false,
  "port": 8880,
  "authorization": "authorizationHeaderString"
}
```

**Comment by Ozymandog** [comment]
> By reinstalling you've updated to the latest version - make sure your `config.json` is up to date with `config.example.json`, it looks like you're missing this block: 
> ```json
> "express": {
>   "enabled": false,
>   "port": 8880,
>   "authorization": "authorizationHeaderString"
> }
> ```
> 

What is that? What do I need to add to that?

**Comment by Ozymandog** [comment]
> By reinstalling you've updated to the latest version - make sure your `config.json` is up to date with `config.example.json`, it looks like you're missing this block: 
> ```json
> "express": {
>   "enabled": false,
>   "port": 8880,
>   "authorization": "authorizationHeaderString"
> }
> ```
> 

What's the authorization and api port where do I find that?

**Comment by Senither** [comment]
You need to make sure the keys from the `config.example.json` file also exists in your `config.json` file, the keys being `express`, `enabled`, `port`, `authorization`, the values is customizable and can be changed to anything you'd like.

The port you set is the port the API will be running on, and the authorization value you set is what is required to be in the request header when you try communicating with the API, if you don't want to use the API you can just copy the keys and values into your config but leave the `enabled` key at false, so the API is never started, and the other values aren't used.

**Comment by Ozymandog** [comment]
> 
> 
> You need to make sure the keys from the `config.example.json` file also exists in your `config.json` file, the keys being `express`, `enabled`, `port`, `authorization`, the values is customizable and can be changed to anything you'd like.
> 
> The port you set is the port the API will be running on, and the authorization value you set is what is required to be in the request header when you try communicating with the API, if you don't want to use the API you can just copy the keys and values into your config but leave the `enabled` key at false, so the API is never started, and the other values aren't used.

okay, thank you
