### ISSUE TITLE
Bot doesn't show join/leave.

### ISSUE THREAD

**Issue by AlyssaXHCM** [Senither/hypixel-discord-chat-bridge#43]
![image](https://user-images.githubusercontent.com/88122765/138661464-15f42ce1-f172-4e64-ac1b-afdaf89aa4bd.png)
Not sure why it doesn't show join/leave. Enabled webhook permissions for bot.

**Comment by itsneyoa** [comment]
Check the bot account doesn't have guild notifications disabled (`/g notifications`)

**Comment by AlyssaXHCM** [comment]
Thank you. Just bought the account and it's already enabled.
