### ISSUE TITLE
Console Issue

### ISSUE THREAD

**Issue by Hoerse-Wacko** [Senither/hypixel-discord-chat-bridge#44]
![t](https://user-images.githubusercontent.com/76411986/141663670-2b6cd8b0-32d5-47c0-a56e-85ec496b6d1d.PNG)
Whenever i start the bot I get this error, any suggestions on how to fix it?

**Comment by M4aXim** [comment]
are you doing it with node or docker?
if with node try to do node . or just try reinstalling bridge

**Comment by itsneyoa** [comment]
Although I can't say for sure I would assume that's the result you get if the device or account are IP banned or account banned, or the IP address you're trying to connect to doesn't exist. Double check the account and your IP address aren't banned and the server address is set correctly in whichever configuration you're using.

**Comment by M4axim** [comment]
I also thought that but this would pop up 
![image](https://user-images.githubusercontent.com/79996174/142755056-9da7a4bb-30b6-48cb-89ae-08746fe059e6.png)

**Comment by Hoerse-Wacko** [comment]
Thank you both for replies, while looking at it I got a new host for the bot and its now all working! So thanks!
