### ISSUE TITLE
Bot keeps repeating being sent to limbo.

### ISSUE THREAD

**Issue by ReedeB** [Senither/hypixel-discord-chat-bridge#53]
bridge_1 | [21:20] Minecraft > Sending Minecraft client to limbo
it repeats that constantly which if it spams the command it will get banned.

**Comment by ReedeB** [comment]
ive tried !relog to and it doesnt help

**Comment by RagingEnby** [comment]
thats purposeful. You dont want a bot to be in a standard lobby. it works just fine while in limbo
